[project]
name = "order-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.92",
    "botocore[crt]>=1.43.92",
    "langchain>=1.4.0",
    "langchain-aws>=1.7.6",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]
